### ISSUE TITLE
Simon's Site - todo

### ISSUE THREAD

**Issue by thomashoddinott** [thomashoddinott/thomashoddinott.github.io#3]
https://thomashoddinott.github.io/simon-site-template/

**General**
- [x] purple accent --> green/navy blue
- [x] create a footer with standard stuff (?)
- [x] SVG graphic logo: SH inside circle - dark on light grey

**Services**
- [x] 1 category (no title)
- [x] Single row of 3 items: {Translation, Interpretting, Proof Reading} 

**Experience**
- [x] change to Qualifications

**Contact**
- [x] remove email form; use mailto href instead on address
- [x] social icons: twitter, linkedin

**Comment by shoddino** [comment]
- [ ]  insert between Services and Qualifications a small section called Portfolio with a single sentence: "Some of the clients to have trusted in my services include: UnipolSai, Coca-Cola Hellenic Bottling Company, AC Milan, Moto Guzzi, Aprilia, Ceetrus Italia, DOMINA, L&B Partners Law Firm, Sisal and many more.

**Comment by shoddino** [comment]
- [ ] localisation of website in DE and IT. In the top right of the page there should be three buttons each separated by a pipe. Mock-up photo provided. Don't know how to implement localisation correctly, but at the end of the day, being a single-page website, you could just create subpages and link them all interdependently via href tags. So create copies of the page and write "German" and "Italian" so I know which ones they are and then I'll fill out the text later.

![Screenshot 2020-12-27 at 13 21 47](https://user-images.githubusercontent.com/46000233/103171750-959df600-4846-11eb-88b4-c4266a8fdc43.png)

**Comment by shoddino** [comment]
- [ ] Test layout on Firefox, Chrome, Safari and then on some mobile devices.

**Comment by thomashoddinott** [comment]
move this up a bit:
![image](https://user-images.githubusercontent.com/65024750/103172082-c67f2a80-4848-11eb-8a57-3d58a9591856.png)

**Comment by hoddinott** [comment]
fixed favicon.
